// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWI4JJqii0S1KurqgU1EJ4a79Mlng4nE',
    appId: '1:342539249605:web:e388a3a65994b4f5ff0dac',
    messagingSenderId: '342539249605',
    projectId: 'storage-demo-dbc2b',
    authDomain: 'storage-demo-dbc2b.firebaseapp.com',
    storageBucket: 'storage-demo-dbc2b.appspot.com',
    measurementId: 'G-GZTH3EQHVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAom8X2-Qnvwxl3AWguDojHbyY7PvPxBus',
    appId: '1:342539249605:android:b8c25f682f3e9ddcff0dac',
    messagingSenderId: '342539249605',
    projectId: 'storage-demo-dbc2b',
    storageBucket: 'storage-demo-dbc2b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDVOPsNVyW-_P5nR5ZyH5rapJlzcIrFkI',
    appId: '1:342539249605:ios:dbf034d04b71149bff0dac',
    messagingSenderId: '342539249605',
    projectId: 'storage-demo-dbc2b',
    storageBucket: 'storage-demo-dbc2b.appspot.com',
    iosClientId: '342539249605-us6j24lofk16os3bnfrpuuchctufmeei.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterfiredemo',
  );
}
